# Generated by Django 4.1.2 on 2022-10-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="town",
            field=models.CharField(default="Portsmouth", max_length=100),
        ),
    ]
